FROM golang@sha256:e401dae1bf814e29204a8cb7915682e1780951e609ca0dd8865ee1937f510c48 AS gosu-builder

RUN git clone https://github.com/tianon/gosu.git /src \
    && cd /src \
    && git checkout --detach 6456aaa0f3c854d199d0f037f068eb97515b7513 \
    && CGO_ENABLED=0 /usr/local/go/bin/go build -trimpath -buildvcs=false -o /gosu . \
    && /gosu --version

FROM mysql@sha256:57c892ddeb17e6c7dddf219914db017b2cf3e2797806a75424444b83622cc8ef

USER root
RUN microdnf remove -y mysql-shell \
    && microdnf \
       --disablerepo=mysql-tools-community \
       --disablerepo=mysqlinnovation-server-minimal \
       update -y \
    && microdnf clean all

COPY --from=gosu-builder /gosu /usr/local/bin/gosu
RUN gosu --version \
    && gosu nobody id -u | grep -qx 65534 \
    && mysql --version | grep -Fq 'Ver 9.5.0 '
