FROM golang@sha256:e401dae1bf814e29204a8cb7915682e1780951e609ca0dd8865ee1937f510c48 AS gosu-builder

RUN git clone https://github.com/tianon/gosu.git /src \
    && cd /src \
    && git checkout --detach 6456aaa0f3c854d199d0f037f068eb97515b7513 \
    && CGO_ENABLED=0 /usr/local/go/bin/go build -trimpath -buildvcs=false -o /gosu . \
    && /gosu --version

FROM mysql@sha256:cbade841779f1661300e705721f9d2ff159865cc7a8a291affbff43ac6ec7f1d

USER root
ARG MYSQL_UID=1999
ARG MYSQL_GID=1999
RUN groupmod --gid "$MYSQL_GID" mysql \
    && usermod --uid "$MYSQL_UID" --gid "$MYSQL_GID" mysql \
    && find /var/lib/mysql /var/run/mysqld -xdev -user 999 -exec chown "$MYSQL_UID:$MYSQL_GID" {} + \
    && microdnf remove -y mysql-shell \
    && microdnf \
       --disablerepo=mysql-tools-community \
       --disablerepo=mysql9.7-server-minimal \
       update -y \
    && microdnf clean all

COPY --from=gosu-builder /gosu /usr/local/bin/gosu
RUN gosu --version \
    && gosu nobody id -u | grep -qx 65534 \
    && test "$(id -u mysql)" -eq "$MYSQL_UID" \
    && test "$(id -g mysql)" -eq "$MYSQL_GID" \
    && mysql --version | grep -Fq 'Ver 9.7.1 '
